### PR TITLE
test: chat bot

### PR DESCRIPTION
**Pull request by nei1ee**
I haven't used `WebSocket` before, so if it should be returned here?

```ts
async askAsync(
  prompt: string,
  handler: (response: Record<string, any>) => void = () => {}
) {
  this.chatHub?.on("final", handler);
  return await this.chatHub?.askAsync(prompt);
}
```

### CODE REVIEW

**Comment by KeJunMao** [comment]
yes, i forgot it.

**Comment by KeJunMao** [comment]
Is it meaningful to use `toMatchInlineSnapshot` ? The response is different every time.

**Comment by nei1ee** [comment]
> Is it meaningful to use `toMatchInlineSnapshot` ? The response is different every time.

It doesn't make that much meaningful to just keep returning `undefined` at first to see what went wrong🤣.

**Comment by KeJunMao** [comment]
OK, I don't think it's good. Do you have any good ideas?

**Comment by nei1ee** [comment]
This test only focus on whether something is returned not the specifics of what, so it feels just fine now.

**Pull request merged**
